"""Curated source registry used by the ingestion experiment."""

from dataclasses import dataclass


@dataclass(frozen=True)
class Source:
    source_id: str
    name: str
    scope: str
    states: tuple[str, ...]
    language: str
    rss_url: str
    active: bool = True
    feed_health: str = "NOT_CHECKED"
    last_error: str | None = None


# These are deliberately kept in code for the first local validation slice.
# Feed health is checked by the ingestion API; a source is not considered
# reliable until it has passed that check repeatedly.
SOURCES: tuple[Source, ...] = (
    Source(
        source_id="the-hindu-india",
        name="The Hindu — India",
        scope="NATIONAL",
        states=(),
        language="EN",
        rss_url="https://www.thehindu.com/news/national/feeder/default.rss",
    ),
    Source(
        source_id="indian-express-india",
        name="The Indian Express — India",
        scope="NATIONAL",
        states=(),
        language="EN",
        rss_url="https://indianexpress.com/section/india/feed/",
    ),
    Source(
        source_id="the-hindu-andhra-pradesh",
        name="The Hindu — Andhra Pradesh",
        scope="STATE",
        states=("Andhra Pradesh",),
        language="EN",
        rss_url="https://www.thehindu.com/news/national/andhra-pradesh/feeder/default.rss",
    ),
    Source(
        source_id="new-indian-express-andhra-pradesh",
        name="The New Indian Express — Andhra Pradesh",
        scope="STATE",
        states=("Andhra Pradesh",),
        language="EN",
        rss_url="https://www.newindianexpress.com/states/andhra-pradesh/feed",
        # Preserved in the registry, but hidden from active runs after live
        # validation returned HTTP 404 for this endpoint.
        active=False,
    ),
    Source(
        source_id="hindustan-times-india",
        name="Hindustan Times — India",
        scope="NATIONAL",
        states=(),
        language="EN",
        rss_url="https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml",
    ),
    Source(
        source_id="ndtv-india",
        name="NDTV — India",
        scope="NATIONAL",
        states=(),
        language="EN",
        rss_url="https://feeds.feedburner.com/ndtvnews-india-news",
    ),
    Source(
        source_id="times-of-india-india",
        name="Times of India — India",
        scope="NATIONAL",
        states=(),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms",
    ),
    Source(
        source_id="theprint-india",
        name="ThePrint — India",
        scope="NATIONAL",
        states=(),
        language="EN",
        rss_url="https://theprint.in/feed/",
    ),
    Source(
        source_id="indian-express-kerala",
        name="The Indian Express — Kerala",
        scope="STATE",
        states=("Kerala",),
        language="EN",
        rss_url="https://indianexpress.com/section/india/kerala/feed/",
    ),
    Source(
        source_id="indian-express-hyderabad",
        name="The Indian Express — Hyderabad",
        scope="REGIONAL",
        states=("Telangana",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/hyderabad/feed/",
    ),
    Source(
        source_id="onmanorama-kerala",
        name="Onmanorama — Kerala",
        scope="STATE",
        states=("Kerala",),
        language="EN",
        rss_url="https://www.onmanorama.com/kerala.feeds.onmrss.xml",
    ),
    Source(
        source_id="ap-herald-english",
        name="AP Herald — English",
        scope="STATE",
        states=("Andhra Pradesh",),
        language="EN",
        rss_url="http://feeds.feedburner.com/apherald-politics-english",
    ),
    Source(
        source_id="the-hans-india-ap-telangana",
        name="The Hans India — Andhra Pradesh & Telangana",
        scope="REGIONAL",
        states=("Andhra Pradesh", "Telangana"),
        language="EN",
        rss_url="https://www.thehansindia.com/feed",
    ),
    Source(
        source_id="the-indian-express-mumbai-maharashtra",
        name="The Indian Express — Mumbai",
        scope="STATE",
        states=("Maharashtra",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/mumbai/feed/",
    ),
    Source(
        source_id="hindustan-times-mumbai-maharashtra",
        name="Hindustan Times — Mumbai",
        scope="STATE",
        states=("Maharashtra",),
        language="EN",
        rss_url="https://www.hindustantimes.com/feeds/rss/cities/mumbai-news/rssfeed.xml",
    ),
    Source(
        source_id="times-of-india-mumbai-maharashtra",
        name="Times of India — Mumbai",
        scope="STATE",
        states=("Maharashtra",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/-2128838597.cms",
    ),
    Source(
        source_id="the-indian-express-pune-maharashtra",
        name="The Indian Express — Pune",
        scope="STATE",
        states=("Maharashtra",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/pune/feed/",
    ),
    Source(
        source_id="hindustan-times-pune-maharashtra",
        name="Hindustan Times — Pune",
        scope="STATE",
        states=("Maharashtra",),
        language="EN",
        rss_url="https://www.hindustantimes.com/feeds/rss/cities/pune-news/rssfeed.xml",
    ),
    Source(
        source_id="times-of-india-pune-maharashtra",
        name="Times of India — Pune",
        scope="STATE",
        states=("Maharashtra",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/-2128821991.cms",
    ),
    Source(
        source_id="the-indian-express-kolkata-west-bengal",
        name="The Indian Express — Kolkata",
        scope="STATE",
        states=("West Bengal",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/kolkata/feed/",
    ),
    Source(
        source_id="hindustan-times-kolkata-west-bengal",
        name="Hindustan Times — Kolkata",
        scope="STATE",
        states=("West Bengal",),
        language="EN",
        rss_url="https://www.hindustantimes.com/feeds/rss/cities/kolkata-news/rssfeed.xml",
    ),
    Source(
        source_id="times-of-india-kolkata-west-bengal",
        name="Times of India — Kolkata",
        scope="STATE",
        states=("West Bengal",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/-2128830821.cms",
    ),
    Source(
        source_id="the-indian-express-lucknow-uttar-pradesh",
        name="The Indian Express — Lucknow",
        scope="STATE",
        states=("Uttar Pradesh",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/lucknow/feed/",
    ),
    Source(
        source_id="hindustan-times-lucknow-uttar-pradesh",
        name="Hindustan Times — Lucknow",
        scope="STATE",
        states=("Uttar Pradesh",),
        language="EN",
        rss_url="https://www.hindustantimes.com/feeds/rss/cities/lucknow-news/rssfeed.xml",
    ),
    Source(
        source_id="times-of-india-lucknow-uttar-pradesh",
        name="Times of India — Lucknow",
        scope="STATE",
        states=("Uttar Pradesh",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/-2128819658.cms",
    ),
    Source(
        source_id="the-indian-express-jaipur-rajasthan",
        name="The Indian Express — Jaipur",
        scope="STATE",
        states=("Rajasthan",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/jaipur/feed/",
    ),
    Source(
        source_id="hindustan-times-jaipur-rajasthan",
        name="Hindustan Times — Jaipur",
        scope="STATE",
        states=("Rajasthan",),
        language="EN",
        rss_url="https://www.hindustantimes.com/feeds/rss/cities/jaipur-news/rssfeed.xml",
    ),
    Source(
        source_id="times-of-india-jaipur-rajasthan",
        name="Times of India — Jaipur",
        scope="STATE",
        states=("Rajasthan",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/3012544.cms",
    ),
    Source(
        source_id="the-indian-express-patna-bihar",
        name="The Indian Express — Patna",
        scope="STATE",
        states=("Bihar",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/patna/feed/",
    ),
    Source(
        source_id="hindustan-times-patna-bihar",
        name="Hindustan Times — Patna",
        scope="STATE",
        states=("Bihar",),
        language="EN",
        rss_url="https://www.hindustantimes.com/feeds/rss/cities/patna-news/rssfeed.xml",
    ),
    Source(
        source_id="times-of-india-patna-bihar",
        name="Times of India — Patna",
        scope="STATE",
        states=("Bihar",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/-2128817995.cms",
    ),
    Source(
        source_id="the-indian-express-bangalore-karnataka",
        name="The Indian Express — Bangalore",
        scope="STATE",
        states=("Karnataka",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/bangalore/feed/",
    ),
    Source(
        source_id="hindustan-times-bengaluru-karnataka",
        name="Hindustan Times — Bengaluru",
        scope="STATE",
        states=("Karnataka",),
        language="EN",
        rss_url="https://www.hindustantimes.com/feeds/rss/cities/bengaluru-news/rssfeed.xml",
    ),
    Source(
        source_id="times-of-india-bangalore-karnataka",
        name="Times of India — Bangalore",
        scope="STATE",
        states=("Karnataka",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/-2128833038.cms",
    ),
    Source(
        source_id="the-indian-express-thiruvananthapuram-kerala",
        name="The Indian Express — Thiruvananthapuram",
        scope="STATE",
        states=("Kerala",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/thiruvananthapuram/feed/",
    ),
    Source(
        source_id="times-of-india-thiruvananthapuram-kerala",
        name="Times of India — Thiruvananthapuram",
        scope="STATE",
        states=("Kerala",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/3831863.cms",
    ),
    Source(
        source_id="new-indian-express-kerala-xml-feed-endpoint-kerala",
        name="New Indian Express — Kerala XML feed endpoint",
        scope="STATE",
        states=("Kerala",),
        language="EN",
        rss_url="https://www.newindianexpress.com/states/kerala?getXmlFeed=true&widgetId=534391&widgetName=rssfeed",
    ),
    Source(
        source_id="the-indian-express-chennai-tamil-nadu",
        name="The Indian Express — Chennai",
        scope="STATE",
        states=("Tamil Nadu",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/chennai/feed/",
    ),
    Source(
        source_id="times-of-india-chennai-tamil-nadu",
        name="Times of India — Chennai",
        scope="STATE",
        states=("Tamil Nadu",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/2950623.cms",
    ),
    Source(
        source_id="times-of-india-coimbatore-tamil-nadu",
        name="Times of India — Coimbatore",
        scope="STATE",
        states=("Tamil Nadu",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/7503091.cms",
    ),
)
