"""Curated source registry used by the ingestion experiment."""

from dataclasses import dataclass


@dataclass(frozen=True)
class Source:
    source_id: str
    name: str
    scope: str
    states: tuple[str, ...]
    language: str
    rss_url: str
    max_entries: int = 50
    active: bool = True
    feed_health: str = "NOT_CHECKED"
    last_error: str | None = None


# These are deliberately kept in code for the first local validation slice.
# Feed health is checked by the ingestion API; a source is not considered
# reliable until it has passed that check repeatedly.
SOURCES: tuple[Source, ...] = (
    Source(
        source_id="the-hindu-india",
        name="The Hindu — India",
        scope="NATIONAL",
        states=(),
        language="EN",
        max_entries=100,
        rss_url="https://www.thehindu.com/news/national/feeder/default.rss",
    ),
    Source(
        source_id="indian-express-india",
        name="The Indian Express — India",
        scope="NATIONAL",
        states=(),
        language="EN",
        max_entries=100,
        rss_url="https://indianexpress.com/section/india/feed/",
    ),
    Source(
        source_id="the-hindu-andhra-pradesh",
        name="The Hindu — Andhra Pradesh",
        scope="STATE",
        states=("Andhra Pradesh",),
        language="EN",
        rss_url="https://www.thehindu.com/news/national/andhra-pradesh/feeder/default.rss",
    ),
    Source(
        source_id="new-indian-express-andhra-pradesh",
        name="The New Indian Express — Andhra Pradesh",
        scope="STATE",
        states=("Andhra Pradesh",),
        language="EN",
        rss_url="https://www.newindianexpress.com/states/andhra-pradesh/feed",
        # Preserved in the registry, but hidden from active runs after live
        # validation returned HTTP 404 for this endpoint.
        active=False,
    ),
    Source(
        source_id="hindustan-times-india",
        name="Hindustan Times — India",
        scope="NATIONAL",
        states=(),
        language="EN",
        max_entries=100,
        rss_url="https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml",
    ),
    Source(
        source_id="ndtv-india",
        name="NDTV — India",
        scope="NATIONAL",
        states=(),
        language="EN",
        max_entries=100,
        rss_url="https://feeds.feedburner.com/ndtvnews-india-news",
    ),
    Source(
        source_id="times-of-india-india",
        name="Times of India — India",
        scope="NATIONAL",
        states=(),
        language="EN",
        max_entries=100,
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms",
    ),
    Source(
        source_id="theprint-india",
        name="ThePrint — India",
        scope="NATIONAL",
        states=(),
        language="EN",
        max_entries=100,
        rss_url="https://theprint.in/feed/",
    ),
    Source(
        source_id="indian-express-kerala",
        name="The Indian Express — Kerala",
        scope="STATE",
        states=("Kerala",),
        language="EN",
        rss_url="https://indianexpress.com/section/india/kerala/feed/",
    ),
    Source(
        source_id="indian-express-hyderabad",
        name="The Indian Express — Hyderabad",
        scope="REGIONAL",
        states=("Telangana",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/hyderabad/feed/",
    ),
    Source(
        source_id="onmanorama-kerala",
        name="Onmanorama — Kerala",
        scope="STATE",
        states=("Kerala",),
        language="EN",
        rss_url="https://www.onmanorama.com/kerala.feeds.onmrss.xml",
    ),
    Source(
        source_id="ap-herald-english",
        name="AP Herald — English",
        scope="STATE",
        states=("Andhra Pradesh",),
        language="EN",
        rss_url="http://feeds.feedburner.com/apherald-politics-english",
    ),
    Source(
        source_id="the-hans-india-ap-telangana",
        name="The Hans India — Andhra Pradesh & Telangana",
        scope="REGIONAL",
        states=("Andhra Pradesh", "Telangana"),
        language="EN",
        rss_url="https://www.thehansindia.com/feed",
    ),
    Source(
        source_id="the-indian-express-mumbai-maharashtra",
        name="The Indian Express — Mumbai",
        scope="STATE",
        states=("Maharashtra",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/mumbai/feed/",
    ),
    Source(
        source_id="hindustan-times-mumbai-maharashtra",
        name="Hindustan Times — Mumbai",
        scope="STATE",
        states=("Maharashtra",),
        language="EN",
        rss_url="https://www.hindustantimes.com/feeds/rss/cities/mumbai-news/rssfeed.xml",
    ),
    Source(
        source_id="times-of-india-mumbai-maharashtra",
        name="Times of India — Mumbai",
        scope="STATE",
        states=("Maharashtra",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/-2128838597.cms",
    ),
    Source(
        source_id="the-indian-express-pune-maharashtra",
        name="The Indian Express — Pune",
        scope="STATE",
        states=("Maharashtra",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/pune/feed/",
    ),
    Source(
        source_id="hindustan-times-pune-maharashtra",
        name="Hindustan Times — Pune",
        scope="STATE",
        states=("Maharashtra",),
        language="EN",
        rss_url="https://www.hindustantimes.com/feeds/rss/cities/pune-news/rssfeed.xml",
    ),
    Source(
        source_id="times-of-india-pune-maharashtra",
        name="Times of India — Pune",
        scope="STATE",
        states=("Maharashtra",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/-2128821991.cms",
    ),
    Source(
        source_id="the-indian-express-kolkata-west-bengal",
        name="The Indian Express — Kolkata",
        scope="STATE",
        states=("West Bengal",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/kolkata/feed/",
    ),
    Source(
        source_id="hindustan-times-kolkata-west-bengal",
        name="Hindustan Times — Kolkata",
        scope="STATE",
        states=("West Bengal",),
        language="EN",
        rss_url="https://www.hindustantimes.com/feeds/rss/cities/kolkata-news/rssfeed.xml",
    ),
    Source(
        source_id="times-of-india-kolkata-west-bengal",
        name="Times of India — Kolkata",
        scope="STATE",
        states=("West Bengal",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/-2128830821.cms",
    ),
    Source(
        source_id="the-indian-express-lucknow-uttar-pradesh",
        name="The Indian Express — Lucknow",
        scope="STATE",
        states=("Uttar Pradesh",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/lucknow/feed/",
    ),
    Source(
        source_id="hindustan-times-lucknow-uttar-pradesh",
        name="Hindustan Times — Lucknow",
        scope="STATE",
        states=("Uttar Pradesh",),
        language="EN",
        rss_url="https://www.hindustantimes.com/feeds/rss/cities/lucknow-news/rssfeed.xml",
    ),
    Source(
        source_id="times-of-india-lucknow-uttar-pradesh",
        name="Times of India — Lucknow",
        scope="STATE",
        states=("Uttar Pradesh",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/-2128819658.cms",
    ),
    Source(
        source_id="the-indian-express-jaipur-rajasthan",
        name="The Indian Express — Jaipur",
        scope="STATE",
        states=("Rajasthan",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/jaipur/feed/",
    ),
    Source(
        source_id="hindustan-times-jaipur-rajasthan",
        name="Hindustan Times — Jaipur",
        scope="STATE",
        states=("Rajasthan",),
        language="EN",
        rss_url="https://www.hindustantimes.com/feeds/rss/cities/jaipur-news/rssfeed.xml",
    ),
    Source(
        source_id="times-of-india-jaipur-rajasthan",
        name="Times of India — Jaipur",
        scope="STATE",
        states=("Rajasthan",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/3012544.cms",
    ),
    Source(
        source_id="the-indian-express-patna-bihar",
        name="The Indian Express — Patna",
        scope="STATE",
        states=("Bihar",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/patna/feed/",
    ),
    Source(
        source_id="hindustan-times-patna-bihar",
        name="Hindustan Times — Patna",
        scope="STATE",
        states=("Bihar",),
        language="EN",
        rss_url="https://www.hindustantimes.com/feeds/rss/cities/patna-news/rssfeed.xml",
    ),
    Source(
        source_id="times-of-india-patna-bihar",
        name="Times of India — Patna",
        scope="STATE",
        states=("Bihar",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/-2128817995.cms",
    ),
    Source(
        source_id="the-indian-express-bangalore-karnataka",
        name="The Indian Express — Bangalore",
        scope="STATE",
        states=("Karnataka",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/bangalore/feed/",
    ),
    Source(
        source_id="hindustan-times-bengaluru-karnataka",
        name="Hindustan Times — Bengaluru",
        scope="STATE",
        states=("Karnataka",),
        language="EN",
        rss_url="https://www.hindustantimes.com/feeds/rss/cities/bengaluru-news/rssfeed.xml",
    ),
    Source(
        source_id="times-of-india-bangalore-karnataka",
        name="Times of India — Bangalore",
        scope="STATE",
        states=("Karnataka",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/-2128833038.cms",
    ),
    Source(
        source_id="the-indian-express-thiruvananthapuram-kerala",
        name="The Indian Express — Thiruvananthapuram",
        scope="STATE",
        states=("Kerala",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/thiruvananthapuram/feed/",
    ),
    Source(
        source_id="times-of-india-thiruvananthapuram-kerala",
        name="Times of India — Thiruvananthapuram",
        scope="STATE",
        states=("Kerala",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/3831863.cms",
    ),
    Source(
        source_id="new-indian-express-kerala-xml-feed-endpoint-kerala",
        name="New Indian Express — Kerala XML feed endpoint",
        scope="STATE",
        states=("Kerala",),
        language="EN",
        rss_url="https://www.newindianexpress.com/states/kerala?getXmlFeed=true&widgetId=534391&widgetName=rssfeed",
    ),
    Source(
        source_id="the-indian-express-chennai-tamil-nadu",
        name="The Indian Express — Chennai",
        scope="STATE",
        states=("Tamil Nadu",),
        language="EN",
        rss_url="https://indianexpress.com/section/cities/chennai/feed/",
    ),
    Source(
        source_id="times-of-india-chennai-tamil-nadu",
        name="Times of India — Chennai",
        scope="STATE",
        states=("Tamil Nadu",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/2950623.cms",
    ),
    Source(
        source_id="times-of-india-coimbatore-tamil-nadu",
        name="Times of India — Coimbatore",
        scope="STATE",
        states=("Tamil Nadu",),
        language="EN",
        rss_url="https://timesofindia.indiatimes.com/rssfeeds/7503091.cms",
    ),
    Source(
        source_id="the-hawk-andhra-pradesh",
        name="The Hawk — Andhra Pradesh",
        scope="STATE",
        states=("Andhra Pradesh",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/andhra-pradesh",
    ),
    Source(
        source_id="the-hawk-arunachal-pradesh",
        name="The Hawk — Arunachal Pradesh",
        scope="STATE",
        states=("Arunachal Pradesh",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/arunachal-pradesh",
    ),
    Source(
        source_id="the-hawk-assam",
        name="The Hawk — Assam",
        scope="STATE",
        states=("Assam",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/assam",
    ),
    Source(
        source_id="the-hawk-bihar",
        name="The Hawk — Bihar",
        scope="STATE",
        states=("Bihar",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/bihar",
    ),
    Source(
        source_id="the-hawk-chhattisgarh",
        name="The Hawk — Chhattisgarh",
        scope="STATE",
        states=("Chhattisgarh",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/chhattisgarh",
    ),
    Source(
        source_id="the-hawk-goa",
        name="The Hawk — Goa",
        scope="STATE",
        states=("Goa",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/goa",
    ),
    Source(
        source_id="the-hawk-gujarat",
        name="The Hawk — Gujarat",
        scope="STATE",
        states=("Gujarat",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/gujarat",
    ),
    Source(
        source_id="the-hawk-haryana",
        name="The Hawk — Haryana",
        scope="STATE",
        states=("Haryana",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/haryana",
    ),
    Source(
        source_id="the-hawk-himachal-pradesh",
        name="The Hawk — Himachal Pradesh",
        scope="STATE",
        states=("Himachal Pradesh",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/himachal-pradesh",
    ),
    Source(
        source_id="the-hawk-jharkhand",
        name="The Hawk — Jharkhand",
        scope="STATE",
        states=("Jharkhand",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/jharkhand",
    ),
    Source(
        source_id="the-hawk-karnataka",
        name="The Hawk — Karnataka",
        scope="STATE",
        states=("Karnataka",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/karnataka",
    ),
    Source(
        source_id="the-hawk-kerala",
        name="The Hawk — Kerala",
        scope="STATE",
        states=("Kerala",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/kerala",
    ),
    Source(
        source_id="the-hawk-madhya-pradesh",
        name="The Hawk — Madhya Pradesh",
        scope="STATE",
        states=("Madhya Pradesh",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/madhya-pradesh",
    ),
    Source(
        source_id="the-hawk-maharashtra",
        name="The Hawk — Maharashtra",
        scope="STATE",
        states=("Maharashtra",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/maharashtra",
    ),
    Source(
        source_id="the-hawk-manipur",
        name="The Hawk — Manipur",
        scope="STATE",
        states=("Manipur",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/manipur",
    ),
    Source(
        source_id="the-hawk-meghalaya",
        name="The Hawk — Meghalaya",
        scope="STATE",
        states=("Meghalaya",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/meghalaya",
    ),
    Source(
        source_id="the-hawk-mizoram",
        name="The Hawk — Mizoram",
        scope="STATE",
        states=("Mizoram",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/mizoram",
    ),
    Source(
        source_id="the-hawk-nagaland",
        name="The Hawk — Nagaland",
        scope="STATE",
        states=("Nagaland",),
        language="EN",
        # Endpoint is published but currently returns an empty template; keep it inactive until verified.
        active=False,
        rss_url="https://api.thehawk.in/rss/states-and-uts/nagaland",
    ),
    Source(
        source_id="the-hawk-odisha",
        name="The Hawk — Odisha",
        scope="STATE",
        states=("Odisha",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/odisha",
    ),
    Source(
        source_id="the-hawk-punjab",
        name="The Hawk — Punjab",
        scope="STATE",
        states=("Punjab",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/punjab",
    ),
    Source(
        source_id="the-hawk-rajasthan",
        name="The Hawk — Rajasthan",
        scope="STATE",
        states=("Rajasthan",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/rajasthan",
    ),
    Source(
        source_id="the-hawk-sikkim",
        name="The Hawk — Sikkim",
        scope="STATE",
        states=("Sikkim",),
        language="EN",
        # Endpoint is published but currently returns an empty template; keep it inactive until verified.
        active=False,
        rss_url="https://api.thehawk.in/rss/states-and-uts/sikkim",
    ),
    Source(
        source_id="the-hawk-tamil-nadu",
        name="The Hawk — Tamil Nadu",
        scope="STATE",
        states=("Tamil Nadu",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/tamil-nadu",
    ),
    Source(
        source_id="the-hawk-telangana",
        name="The Hawk — Telangana",
        scope="STATE",
        states=("Telangana",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/telangana",
    ),
    Source(
        source_id="the-hawk-tripura",
        name="The Hawk — Tripura",
        scope="STATE",
        states=("Tripura",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/tripura",
    ),
    Source(
        source_id="the-hawk-uttar-pradesh",
        name="The Hawk — Uttar Pradesh",
        scope="STATE",
        states=("Uttar Pradesh",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/uttar-pradesh",
    ),
    Source(
        source_id="the-hawk-uttarakhand",
        name="The Hawk — Uttarakhand",
        scope="STATE",
        states=("Uttarakhand",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/uttarakhand",
    ),
    Source(
        source_id="the-hawk-west-bengal",
        name="The Hawk — West Bengal",
        scope="STATE",
        states=("West Bengal",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/west-bengal",
    ),
    Source(
        source_id="the-hawk-andaman-and-nicobar",
        name="The Hawk — Andaman and Nicobar Islands",
        scope="UT",
        states=("Andaman and Nicobar Islands",),
        language="EN",
        # Endpoint is published but currently returns an empty template; keep it inactive until verified.
        active=False,
        rss_url="https://api.thehawk.in/rss/states-and-uts/andaman-and-nicobar",
    ),
    Source(
        source_id="the-hawk-chandigarh",
        name="The Hawk — Chandigarh",
        scope="UT",
        states=("Chandigarh",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/chandigarh",
    ),
    Source(
        source_id="the-hawk-dadra-and-nagar-havel",
        name="The Hawk — Dadra and Nagar Haveli and Daman and Diu",
        scope="UT",
        states=("Dadra and Nagar Haveli and Daman and Diu",),
        language="EN",
        # Endpoint is published but currently returns an empty template; keep it inactive until verified.
        active=False,
        rss_url="https://api.thehawk.in/rss/states-and-uts/dadra-and-nagar-havel",
    ),
    Source(
        source_id="the-hawk-delhi",
        name="The Hawk — Delhi",
        scope="UT",
        states=("Delhi",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/delhi",
    ),
    Source(
        source_id="the-hawk-jammu-and-kashmir",
        name="The Hawk — Jammu & Kashmir",
        scope="UT",
        states=("Jammu & Kashmir",),
        language="EN",
        rss_url="https://api.thehawk.in/rss/states-and-uts/jammu-and-kashmir",
    ),
    Source(
        source_id="the-hawk-lakshadweep",
        name="The Hawk — Lakshadweep",
        scope="UT",
        states=("Lakshadweep",),
        language="EN",
        # Endpoint is published but currently returns an empty template; keep it inactive until verified.
        active=False,
        rss_url="https://api.thehawk.in/rss/states-and-uts/lakshadweep",
    ),
    Source(
        source_id="the-hawk-pondicherry",
        name="The Hawk — Puducherry",
        scope="UT",
        states=("Puducherry",),
        language="EN",
        # Endpoint is published but currently returns an empty template; keep it inactive until verified.
        active=False,
        rss_url="https://api.thehawk.in/rss/states-and-uts/pondicherry",
    ),

    Source(
        source_id="india-today-home",
        name="India Today — Home",
        scope="NATIONAL",
        states=(),
        language="EN",
        max_entries=100,
        rss_url="https://www.indiatoday.in/rss/home",
    ),
    Source(
        source_id="india-today-nation",
        name="India Today — Nation",
        scope="NATIONAL",
        states=(),
        language="EN",
        max_entries=100,
        rss_url="https://www.indiatoday.in/rss/1206514",
    ),
    Source(
        source_id="national-herald-india",
        name="National Herald — India",
        scope="NATIONAL",
        states=(),
        language="EN",
        # Endpoint responded but returned no parseable articles in validation.
        active=False,
        max_entries=50,
        rss_url="https://www.nationalheraldindia.com/stories.rss?section=india",
    ),
    Source(
        source_id="tribune-punjab",
        name="The Tribune — Punjab",
        scope="STATE",
        states=("Punjab",),
        language="EN",
        rss_url="https://publish.tribuneindia.com/state/punjab/feed/",
    ),
    Source(
        source_id="tribune-haryana",
        name="The Tribune — Haryana",
        scope="STATE",
        states=("Haryana",),
        language="EN",
        rss_url="https://publish.tribuneindia.com/state/haryana/feed/",
    ),
    Source(
        source_id="tribune-himachal-pradesh",
        name="The Tribune — Himachal Pradesh",
        scope="STATE",
        states=("Himachal Pradesh",),
        language="EN",
        rss_url="https://publish.tribuneindia.com/state/himachal/feed/",
    ),
    Source(
        source_id="tribune-jammu-and-kashmir",
        name="The Tribune — Jammu & Kashmir",
        scope="UT",
        states=("Jammu & Kashmir",),
        language="EN",
        rss_url="https://publish.tribuneindia.com/state/j-k/feed/",
    ),
    Source(
        source_id="tribune-chhattisgarh",
        name="The Tribune — Chhattisgarh",
        scope="STATE",
        states=("Chhattisgarh",),
        language="EN",
        rss_url="https://publish.tribuneindia.com/state/chhattisgarh/feed/",
    ),
    Source(
        source_id="tribune-madhya-pradesh",
        name="The Tribune — Madhya Pradesh",
        scope="STATE",
        states=("Madhya Pradesh",),
        language="EN",
        rss_url="https://publish.tribuneindia.com/state/madhya-pradesh/feed/",
    ),
    Source(
        source_id="tribune-rajasthan",
        name="The Tribune — Rajasthan",
        scope="STATE",
        states=("Rajasthan",),
        language="EN",
        rss_url="https://publish.tribuneindia.com/state/rajasthan/feed/",
    ),
    Source(
        source_id="tribune-uttarakhand",
        name="The Tribune — Uttarakhand",
        scope="STATE",
        states=("Uttarakhand",),
        language="EN",
        rss_url="https://publish.tribuneindia.com/state/uttarakhand/feed/",
    ),
    Source(
        source_id="tribune-uttar-pradesh",
        name="The Tribune — Uttar Pradesh",
        scope="STATE",
        states=("Uttar Pradesh",),
        language="EN",
        rss_url="https://publish.tribuneindia.com/state/uttar-pradesh/feed/",
    ),
    Source(
        source_id="tribune-chandigarh",
        name="The Tribune — Chandigarh",
        scope="UT",
        states=("Chandigarh",),
        language="EN",
        rss_url="https://publish.tribuneindia.com/city/chandigarh/feed/",
    ),
    Source(
        source_id="tribune-delhi",
        name="The Tribune — Delhi",
        scope="UT",
        states=("Delhi",),
        language="EN",
        rss_url="https://publish.tribuneindia.com/city/delhi/feed/",
    ),
)
